"""
AURORA 1.0 — Pydantic Models (Pydantic v2)
All request/response shapes, DB models, and AI result types.
"""
from __future__ import annotations

from typing import Any
from enum import Enum

from pydantic import BaseModel, ConfigDict, EmailStr, Field, field_validator


# ─────────────────────────────────────────────
# ENUMS
# ─────────────────────────────────────────────

class LeadTier(str, Enum):
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"
    UNSCORED = "unscored"


class LeadStatus(str, Enum):
    NEW = "new"
    CALL_INITIATED = "call_initiated"
    CALL_COMPLETED = "call_completed"
    MEETING_BOOKED = "meeting_booked"
    FOLLOW_UP_NEEDED = "follow_up_needed"
    NURTURE_QUEUE = "nurture_queue"
    CLOSED_LOST = "closed_lost"
    NOT_ACTIVE = "not_active"


class ImprovementImpact(str, Enum):
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"


class ImprovementStatus(str, Enum):
    PENDING = "pending_review"
    APPLIED = "applied"
    REJECTED = "rejected"


# ─────────────────────────────────────────────
# LEAD MODELS
# ─────────────────────────────────────────────

class LeadCreate(BaseModel):
    """Inbound form submission from landing page"""
    name: str = Field(..., min_length=2, max_length=100)
    email: EmailStr
    phone: str | None = None
    company: str | None = None
    lead_volume: str | None = None
    message: str | None = None

    @field_validator("phone")
    @classmethod
    def validate_phone(cls, v: str | None) -> str | None:
        if v:
            cleaned = v.replace(" ", "").replace("-", "").replace("(", "").replace(")", "")
            if len(cleaned) < 7:
                raise ValueError("Phone number too short")
        return v


class LeadScore(BaseModel):
    """AI scoring result: 0-100 score, tier, and ICP reasoning."""
    score: int = Field(..., ge=0, le=100)
    tier: LeadTier
    reasoning: str = ""
    icp_fit: bool = False
    urgency: str = ""
    budget_signals: list[str] = Field(default_factory=list)
    recommended_delay_minutes: int = 60


class LeadResponse(BaseModel):
    """API response returned to the landing page after lead submission."""
    id: str
    status: str
    score: int
    tier: LeadTier
    message: str


# ─────────────────────────────────────────────
# CALL / CRITIQUE MODELS
# ─────────────────────────────────────────────

class GeoRegion(str, Enum):
    INDIA = "india"
    US = "us"
    UK = "uk"
    GLOBAL = "global"


class CallScores(BaseModel):
    """9-dimensional call performance scores (0-100 each) + weighted overall."""
    opening: int = Field(0, ge=0, le=100)
    discovery: int = Field(0, ge=0, le=100)
    rapport: int = Field(0, ge=0, le=100)
    objection_handling: int = Field(0, ge=0, le=100)
    closing: int = Field(0, ge=0, le=100)
    naturalness: int = Field(0, ge=0, le=100)
    relevance: int = Field(0, ge=0, le=100)
    pacing: int = Field(0, ge=0, le=100)           # Conversation tempo — not rushing or dragging
    silence_handling: int = Field(0, ge=0, le=100) # Uses pauses effectively, not filling every gap
    overall: int = Field(0, ge=0, le=100)          # Weighted composite of all 9 dimensions


class ScriptImprovement(BaseModel):
    """A single script improvement suggestion generated by the critique engine."""
    category: str
    current_behavior: str
    suggested_behavior: str
    example_script: str
    impact: ImprovementImpact


class ProspectAnalysis(BaseModel):
    """Structured intelligence about the prospect extracted from the call transcript."""
    pain_points: list[str] = []
    buying_stage: str = "unknown"   # awareness | consideration | decision | unknown
    sentiment_overall: str = "neutral"   # positive | neutral | negative | hostile
    budget_signals: str = ""
    objections_raised: list[str] = []


class CallCritique(BaseModel):
    """Full 9-category critique result returned by critique_call()."""
    call_id: str
    scores: CallScores
    overall_score: int
    one_line_summary: str
    meeting_booked: bool = False
    should_follow_up: bool = True
    follow_up_strategy: str = ""   # email | call | whatsapp | sms | none
    estimated_deal_probability: int = 0
    prospect_analysis: ProspectAnalysis = Field(default_factory=ProspectAnalysis)
    action_items: list[str] = []
    script_improvements: list[ScriptImprovement] = []
    coach_verdict: str = ""


class VapiWebhookPayload(BaseModel):
    """Inbound Vapi webhook event — extra fields allowed (Vapi schema evolves)."""
    model_config = ConfigDict(extra="allow")

    message: dict | None = None
    call: dict | None = None


# ─────────────────────────────────────────────
# SELF-IMPROVEMENT / MARS MODELS
# ─────────────────────────────────────────────

class PatternAnalysis(BaseModel):
    """A recurring failure pattern identified during MARS meta-analysis."""
    issue: str
    frequency: int
    impact: str
    example_from_calls: str


class PromptUpdate(BaseModel):
    """New Vapi system prompt generated by the MARS improvement cycle."""
    patterns: list[PatternAnalysis]
    updated_system_prompt: str   # complete deployable prompt text (min 500 words)
    changelog: str               # specific measurable changes made
    expected_improvement_areas: list[str]


class PromptModule(BaseModel):
    """Modular prompt section targeted by MCTS for diff-based editing."""
    module_name: str          # 'opening' | 'discovery' | 'objection' | 'closing' | 'persona'
    content: str              # The actual prompt text for this module
    version: int = 1
    score_delta: float = 0.0  # Measured improvement since last version


class MCTSNode(BaseModel):
    """Budget-aware MCTS planning node for the MARS improvement loop."""
    module: str               # Which prompt module this node targets
    proposed_change: str      # Human-readable description of the change
    expected_score_delta: float  # Expected improvement (0–20 typical)
    estimated_tokens: int     # Compute cost estimate
    mcts_reward: float = 0.0  # score_delta / (tokens / 1000) — higher = more efficient
    depth: int = 0


class MARSLesson(BaseModel):
    """A lesson extracted from a call batch and stored in the mars_lessons table."""
    lesson_type: str          # 'pattern' | 'objection' | 'opening' | 'insight' | 'geo'
    content: str              # The lesson text
    source_calls: int = 1     # How many calls contributed to this lesson
    avg_score_delta: float = 0.0  # Score improvement observed after applying
    mcts_reward: float = 0.0
    geo_region: str | None = None  # Geo-specific lesson if applicable


# ─────────────────────────────────────────────
# DASHBOARD / STATS MODELS
# ─────────────────────────────────────────────

class DashboardStats(BaseModel):
    """Response model for GET /api/stats — all live KPIs aggregated for the dashboard."""
    total_leads: int = 0
    calls_made: int = 0
    meetings_booked: int = 0
    avg_call_score: float = 0.0
    conversion_rate: float = 0.0
    total_cost_usd: float = 0.0
    pending_improvements: int = 0
    active_prompt_version: int = 1
    active_nurture_sequences: int = 0   # Aurora 1.0: nurture pipeline count


# ─────────────────────────────────────────────
# NURTURE SEQUENCE MODELS
# ─────────────────────────────────────────────

class NurtureSequenceType(str, Enum):
    HOT = "hot_nurture"
    WARM = "warm_nurture"
    COLD = "cold_nurture"


class NurtureStepStatus(str, Enum):
    PENDING = "pending"
    DONE = "done"
    FAILED = "failed"
    SKIPPED = "skipped"


class NurtureStep(BaseModel):
    """A single step in a nurture sequence (email, call, or whatsapp)."""
    step: int
    type: str                          # "email" | "call" | "whatsapp"
    delay_hours: int
    template: str | None = None        # None for call-only steps (e.g. exotel)
    provider: str | None = None        # "exotel" | "vapi" | None (email/whatsapp)
    scheduled_at: str | None = None
    status: str = "pending"            # pending | sent | skipped | failed
    result: str = ""


class NurtureSequenceCreate(BaseModel):
    """Request body for manually creating a nurture sequence via API."""
    lead_email: EmailStr
    lead_name: str | None = None
    lead_company: str | None = None
    lead_score: int = 50
    phone: str | None = None
    pain_points: list[str] = []
    call_summary: str | None = None
    geo_region: str = "global"
    should_follow_up: bool = True


class NurtureSequenceResponse(BaseModel):
    """Response model for nurture sequence API endpoints."""
    id: str
    lead_email: str
    lead_name: str | None = None
    sequence_type: str
    current_step: int = 0
    steps: list[Any] = []
    is_active: bool = True
    completed: bool = False
    created_at: str | None = None
    last_action_at: str | None = None


# ─────────────────────────────────────────────
# PROVIDER / HEALTH MODELS
# ─────────────────────────────────────────────

class ProviderCallStats(BaseModel):
    """Per-provider call statistics returned by GET /api/provider-stats."""
    provider: str
    calls: int = 0
    successes: int = 0
    failures: int = 0
    avg_latency_ms: float = 0.0
    last_used: str | None = None
