"""
AURORA 1.0 — MARS: Meta-Analysis Reinforcement System
Budget-aware MCTS planner for autonomous prompt improvement.

Architecture:
  MCTSNode (dataclass) — tree node with reward / compute_cost scoring
  plan_improvements()  — greedy selection within MARS_BUDGET_MINUTES
  expand_node()        — generate child nodes from sub-actions
  run_mcts_planner()   — full pipeline: candidates → ranked MCTSNodes
  insert_mars_lesson() — thin async wrapper around db.supabase helper

Constants:
  MARS_CYCLE_THRESHOLD = 25   # fire every N completed calls
  MARS_BUDGET_MINUTES  = 60   # max total compute-cost per improvement cycle
"""
from __future__ import annotations

import logging
import math
from dataclasses import dataclass, field

logger = logging.getLogger("aurora.mars")

# ─── MARS constants ───────────────────────────────────────────────────────────

MARS_CYCLE_THRESHOLD: int = 25   # Run improvement cycle every N calls
MARS_BUDGET_MINUTES: float = 60  # Max cumulative compute_cost per cycle (minutes)

# Impact → expected score delta lookup (used when no explicit delta given)
_IMPACT_DELTA: dict[str, float] = {
    "high":   8.0,
    "medium": 3.5,
    "low":    1.5,
}

# Module → base cost estimate in minutes (LLM rewrite + Vapi patch overhead)
_MODULE_BASE_COST: dict[str, float] = {
    "opening":          2.0,
    "discovery":        2.5,
    "objection":        3.0,
    "objection_handling": 3.0,
    "closing":          2.0,
    "naturalness":      1.5,
    "pacing":           1.5,
    "persona":          4.0,
    "general":          2.5,
}


# ─── MCTSNode dataclass ───────────────────────────────────────────────────────

@dataclass
class MCTSNode:
    """
    A node in the MCTS planning tree.

    Fields
    ------
    module       : Which prompt module this node targets
                   (opening | discovery | objection | closing | naturalness | pacing | persona)
    action       : Human-readable description of the proposed change
    reward       : Expected score improvement (0–20 typical; higher is better)
    compute_cost : Estimated cost in minutes for this improvement
                   (LLM call + Vapi patch round-trip + safety margin)
    children     : Child nodes generated by expand_node() for sub-actions
    depth        : Tree depth (0 = root candidate)
    """
    module: str
    action: str
    reward: float
    compute_cost: float
    children: list[MCTSNode] = field(default_factory=list)
    depth: int = 0

    @property
    def score(self) -> float:
        """Efficiency score: reward per minute of compute budget consumed."""
        return self.reward / max(self.compute_cost, 0.01)

    def __repr__(self) -> str:
        return (
            f"MCTSNode(module={self.module!r}, score={self.score:.2f}, "
            f"reward={self.reward:.1f}, cost={self.compute_cost:.1f}min, "
            f"action={self.action[:50]!r})"
        )


# ─── Tree operations ──────────────────────────────────────────────────────────

def expand_node(parent: MCTSNode, sub_actions: list[dict]) -> list[MCTSNode]:
    """
    Expand a parent node into child nodes.

    Each sub_action dict may contain:
        action: str, reward: float, compute_cost: float (all optional)
    Missing values inherit from parent (with small decay).
    """
    children: list[MCTSNode] = []
    for sa in sub_actions:
        child = MCTSNode(
            module=parent.module,
            action=sa.get("action", parent.action),
            reward=float(sa.get("reward", parent.reward * 0.7)),   # child typically less impactful
            compute_cost=float(sa.get("compute_cost", parent.compute_cost * 0.6)),
            depth=parent.depth + 1,
        )
        children.append(child)
        parent.children.append(child)
    return children


def mcts_score(node: MCTSNode) -> float:
    """
    MCTS reward-efficiency score (also available as node.score property).
    Reward = expected_score_delta / compute_cost_minutes
    UCB-style: higher compute_cost nodes penalised naturally.
    """
    return node.score


# ─── Planner ─────────────────────────────────────────────────────────────────

def plan_improvements(
    candidates: list[MCTSNode],
    budget_minutes: float = MARS_BUDGET_MINUTES,
    max_nodes: int = 10,
) -> list[MCTSNode]:
    """
    Greedy selection of improvement nodes within the compute budget.

    Algorithm
    ---------
    1. Sort candidates descending by efficiency score (reward / compute_cost)
    2. Greedily add nodes until budget_minutes is exhausted
    3. Skip nodes whose cost would exceed remaining budget
    4. Return selected nodes (ordered by priority)

    Parameters
    ----------
    candidates     : All candidate MCTSNodes from run_mcts_planner()
    budget_minutes : Max cumulative compute_cost allowed (default: MARS_BUDGET_MINUTES)
    max_nodes      : Hard cap on number of nodes selected

    Returns
    -------
    list[MCTSNode] sorted by priority (highest efficiency first)
    """
    ranked = sorted(candidates, key=lambda n: n.score, reverse=True)
    selected: list[MCTSNode] = []
    budget_used: float = 0.0

    for node in ranked:
        if len(selected) >= max_nodes:
            break
        if budget_used + node.compute_cost <= budget_minutes:
            selected.append(node)
            budget_used += node.compute_cost
        # Don't break — a later smaller node may still fit

    logger.info(
        f"[MARS] MCTS selected {len(selected)}/{len(candidates)} candidates "
        f"({budget_used:.1f}/{budget_minutes:.0f} min budget used)"
    )
    return selected


def run_mcts_planner(
    improvements: list[dict],
    avg_score: float = 60.0,
    budget_minutes: float = MARS_BUDGET_MINUTES,
) -> list[MCTSNode]:
    """
    Build MCTSNodes from raw improvement dicts and select top candidates.

    Each improvement dict (from get_pending_improvements) is expected to have:
        improvement_type / category : str  — maps to module
        impact                      : str  — 'high' | 'medium' | 'low'
        current_behavior            : str
        suggested_behavior          : str
        expected_delta              : float (optional — inferred from impact)
        compute_cost_minutes        : float (optional — inferred from module)

    Returns improvements ranked by reward/cost, filtered within budget.
    """
    # Group by module to batch-patch related changes together
    by_module: dict[str, list[dict]] = {}
    for imp in improvements:
        module = (imp.get("improvement_type") or imp.get("category") or "general").lower()
        by_module.setdefault(module, []).append(imp)

    candidates: list[MCTSNode] = []

    for module, imps in by_module.items():
        # Aggregate reward: sum of per-improvement deltas (with diminishing returns)
        total_reward: float = 0.0
        for i, imp in enumerate(imps):
            impact = imp.get("impact", "medium").lower()
            delta = float(imp.get("expected_delta", _IMPACT_DELTA.get(impact, 2.0)))
            # Diminishing returns: each additional improvement in same module contributes less
            total_reward += delta * (0.8 ** i)

        # Compute cost: base module cost + per-improvement overhead
        base_cost = _MODULE_BASE_COST.get(module, 2.5)
        compute_cost = base_cost + (len(imps) * 0.3)

        action = (
            f"Apply {len(imps)} improvement(s) to [{module}] module: "
            + "; ".join(
                (imp.get("suggested_behavior") or imp.get("current_behavior") or "")[:60]
                for imp in imps[:2]
            )
        )

        node = MCTSNode(
            module=module,
            action=action,
            reward=round(total_reward, 2),
            compute_cost=round(compute_cost, 2),
            depth=0,
        )
        candidates.append(node)

    return plan_improvements(candidates, budget_minutes=budget_minutes)


# ─── DB convenience wrapper ───────────────────────────────────────────────────

async def insert_mars_lesson(
    lesson_type: str,
    content: str,
    source_calls: int = 1,
    avg_score_delta: float = 0.0,
    mcts_reward: float = 0.0,
    geo_region: str | None = None,
) -> dict:
    """
    Save a MARS lesson to the mars_lessons table via the central DB layer.

    Lessons are long-term memory that persist across improvement cycles —
    they inform future MCTS planning even after a Vapi prompt is updated.

    Parameters
    ----------
    lesson_type   : 'pattern' | 'objection' | 'opening' | 'insight' | 'geo'
    content       : The actionable lesson text
    source_calls  : Number of calls that produced this lesson
    avg_score_delta : Measured or expected score improvement from applying it
    mcts_reward   : Efficiency score stored for future planner reference
    geo_region    : Optional region tag ('india' | 'us' | 'uk' | 'global')

    Returns
    -------
    Inserted row dict from Supabase
    """
    from db.supabase import insert_mars_lesson as _db_insert

    record: dict = {
        "lesson_type":     lesson_type,
        "content":         content,
        "source_calls":    source_calls,
        "avg_score_delta": avg_score_delta,
        "mcts_reward":     mcts_reward,
    }
    if geo_region is not None:
        record["geo_region"] = geo_region

    result = await _db_insert(record)
    logger.info(f"[MARS] Lesson stored: [{lesson_type}] {content[:60]}")
    return result
